<%@ Page Title="" Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="Addcategory.aspx.cs" Inherits="admin_admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <title>Ringing Beauty | Add Category</title>
     <style>
     .gridview-header {
             border-bottom: 1px solid black;
             margin-bottom:2px;
         }
     table tr{
         height:40px;
     }
     </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="row">
    <div class="col-md-10 col-12 col-xl-8 mx-auto p-2">
        <div class="card m-2">
             <div class="card-header">
                 <h5 class="mb-0">ADD CATEGORY</h5>
             </div>
            <div class="card-body">
               <div class="mb-2">
                    <asp:TextBox ID="txtname" runat="server" placeholder="Enter Category Name" 
                         CssClass="form-control" ></asp:TextBox>
                     <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                         ControlToValidate="txtname" ErrorMessage="Enter Category" 
                         ForeColor="#CC0000"></asp:RequiredFieldValidator>
               </div>
                <div>
                     <asp:Button ID="btnadd" runat="server"  CssClass="btn btn-success" 
                      Text="ADD"  onclick="btnadd_Click"  />
                </div>
               <div class="mt-2">
                    <asp:Label ID="lbl" class="text-success" runat="server"></asp:Label>
               </div>
                
       
            </div>
        </div>
        
        <div class="card shadow border-0 mb-7 m-2">
                    <div class="card-header">
                        <h5 class="mb-0">CATEGORIES</h5>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover table-nowrap">
   
                        <tr>
                            <td>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
                        DataKeyNames="CID"
                        onrowcancelingedit="GridView1_RowCancelingEdit1" 
                        onrowdeleting="GridView1_RowDeleting1" onrowediting="GridView1_RowEditing1" 
                        onrowupdating="GridView1_RowUpdating1" AutoGenerateColumns="False" 
                        onselectedindexchanged="GridView1_SelectedIndexChanged" 
                        BackColor="White" BorderColor="#CCCCCC"  Width="885px" 
                        BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" 
                        GridLines="Horizontal">
                
                        <Columns>
                        <asp:CommandField CausesValidation="false" ShowEditButton="true" />
                            <asp:BoundField DataField="CNAME" HeaderText="CATEGORY" 
                                SortExpression="CNAME" />
                        </Columns>
                        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                        <HeaderStyle Font-Bold="True" Height="70" CssClass="gridview-header"  />
                        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F7F7F7" />
                        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                        <SortedDescendingCellStyle BackColor="#E5E5E5" />
                        <SortedDescendingHeaderStyle BackColor="#242121" />
                    </asp:GridView>
                            </td>
                        </tr>
            
                        </table>
                </div>
            </div>
        </div>
        </div>
    
</asp:Content>

